spring.application.name=ReportsGeneration


logging.pattern.console=[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} %-40logger{35} %msg%n

# Referencia al archivo de configuracion de correo electronico
spring.config.import=optional:classpath:mail.properties