spring.application.name=ReportsGeneration


reportproperties.emailDestinationReport=sistemas.automatizados@kranon.com
reportproperties.destinationEmailCopyReport=amonroy@kranon.com,ucortez@kranon.com
reportproperties.destinationEmailCopyHideReport=

reportproperties.hostSFTP=52.171.56.213
reportproperties.portSFTP=22
reportproperties.userSFTP=purecloud
reportproperties.passwordSFTP=spld=Lx*wr=nlR1d&2ra


#reportproperties.hostSFTP=10.0.0.4
#reportproperties.portSFTP=22
#reportproperties.userSFTP=purecloud
#reportproperties.passwordSFTP=z94r73#!Vite$E1?+ith


reportproperties.company=UNITEC
reportproperties.pathOutboundSFTP=/OUTBOUND/A3S/
reportproperties.pathInbuoundSFTP=/INBOUND/A3S/
reportproperties.pathAgenteSFTP=/ESTADOS_AGENTES/A3S/
reportproperties.pathRedesSFTP=/SOCIAL/A3S/

reportproperties.validarSFTP=true
reportproperties.checkFileExists=true


reportproperties.pathLocalOutboundSFTP=D:\\appl\\A3S\\outbound\\
reportproperties.pathLocalInbuoundSFTP=D:\\appl\\A3S\\inbound\\
reportproperties.pathLocalAgenteSFTP=D:\\appl\\A3S\\estados_agente\\
reportproperties.pathLocalRedesSFTP=D:\\appl\\A3S\\redes_sociales\\


reportproperties.vsPathCredencialesAuth=D:\\appl\\software\\NotificacionReportesA3S\\kranoncloud.json
