timeZoneOffset=-6
fileNamePrefix=04-15_outbound
fileNameDateFormat=yyyy

sqlStringConnection=jdbc:sqlserver://127.0.0.1:1433;databaseName=insertcontactunitec;trustServerCertificate=true;user=sqlserver;password=Kranon01#;
sqlQuery=SELECT  [contactId], [contactListId], [NPersona],     CASE    WHEN [FInsercion] LIKE '____-__-__T__:__:__' THEN CONVERT(DATETIME2, [FInsercion], 126)       WHEN TRY_CONVERT(DATETIME, [FInsercion], 126) IS NOT NULL THEN CONVERT(DATETIME, [FInsercion], 126)       WHEN TRY_CONVERT(DATETIME, [FInsercion], 127) IS NOT NULL THEN CONVERT(DATETIME, [FInsercion], 127)       WHEN TRY_CONVERT(DATETIME, [FInsercion], 120) IS NOT NULL THEN CONVERT(DATETIME, [FInsercion], 120)       WHEN TRY_CONVERT(DATETIME, [FInsercion], 121) IS NOT NULL THEN CONVERT(DATETIME, [FInsercion], 121)        ELSE NULL    END AS [FInsercion] FROM  [insertcontactunitec].[dbo].[pc_oldcontacts_V2]  union  SELECT  [contactId], [contactListId], [NPersona],     CASE    WHEN [FInsercion] LIKE '____-__-__T__:__:__' THEN CONVERT(DATETIME2, [FInsercion], 126)       WHEN TRY_CONVERT(DATETIME, [FInsercion], 126) IS NOT NULL THEN CONVERT(DATETIME, [FInsercion], 126)       WHEN TRY_CONVERT(DATETIME, [FInsercion], 127) IS NOT NULL THEN CONVERT(DATETIME, [FInsercion], 127)       WHEN TRY_CONVERT(DATETIME, [FInsercion], 120) IS NOT NULL THEN CONVERT(DATETIME, [FInsercion], 120)       WHEN TRY_CONVERT(DATETIME, [FInsercion], 121) IS NOT NULL THEN CONVERT(DATETIME, [FInsercion], 121)       ELSE NULL    END AS [FInsercion] FROM  [insertcontactunitec].[dbo].pc_insintermedia_V2
SFsqlStringConnection=jdbc:snowflake://esb40608.us-east-1.snowflakecomputing.com/?warehouse=A3S_GCD_CANADA&db=A3S_GCD_CANADA&role=CONSUMERAGENT_CANADA;
dbUser=soporte.tecnico@kranon.com
dbPass=Kr4n0n2023.$
dbDH=A3S_GCD_CANADA
dbName=A3S_GCD_CANADA
dbRole=CONSUMERAGENT_CANADA
intervalo=2026-04-15T14:00:00.000Z/2026-04-15T22:00:00.000Z
##Opciones SFTP
SFTPHost=52.171.56.213
SFTPUser=purecloud
SFTPPassword=spld=Lx*wr=nlR1d&2ra
SFTPPort=22
SFTPPath=/OUTBOUND/A3S/
